Repository time-series-machine-learning/tsml-eval, pull requests merged in 2024-07, with the labels that each got.

#249 [ENH] Implemented r clustering
  tsml_eval/estimators/clustering/__init__.py
  tsml_eval/estimators/clustering/_r_clustering/__init__.py
  tsml_eval/estimators/clustering/_r_clustering/_r_clustering.py
  tsml_eval/estimators/clustering/_r_clustering/_r_clustering_minirocket.py
Labels: enhancement, estimators

#252 [MNT] pre-commit workflow fix
  .github/workflows/pr_pre_commit.yml
Labels: maintenance

#248 [ENH] Forecasting ETSCALC function
  tsml_eval/_wip/forecasting/exponential_smoothing.py
Labels: enhancement

#258 [MNT] CI updates
  .github/workflows/issue_comment_edited.yml
  .github/workflows/periodic_github_maintenace.yml
  .github/workflows/periodic_tests.yml
  .github/workflows/pr_precommit.yml
  .github/workflows/precommit_autoupdate.yml
  .github/workflows/release.yml
  build_tools/comment_pr_labeler.py
  build_tools/pr_labeler.py
  build_tools/pr_open_commenter.py
  build_tools/pr_welcome_edited.py
Labels: maintenance

#259 [MNT] Update aeon
  .github/workflows/scorecard.yml
  pyproject.toml
  tsml_eval/estimators/clustering/tests/test_r_clustering.py
  tsml_eval/experiments/set_classifier.py
  tsml_eval/experiments/set_clusterer.py
Labels: maintenance

#265 [MNT] Workflow fix and redundant files
  .github/workflows/scorecard.yml
  _tsml_group_experiments/soton/clustering_experiments.sh
  _tsml_group_experiments/soton/iridis.txt
Labels: maintenance

#266 [MNT] scorecard fix
  .github/workflows/scorecard.yml
  README.md
Labels: maintenance

#267 [DOC] Update README.md
  README.md
Labels: documentation

#269 [ENH] `_wip` tidy and PF
  .pre-commit-config.yaml
  pyproject.toml
  tsml_eval/_wip/classification/shapelet_based/__init__.py
  tsml_eval/_wip/experiments/results_summary.py
  tsml_eval/_wip/pf/__init__.py
  tsml_eval/_wip/pf/pf.py
  tsml_eval/_wip/shapelets/__init__.py
  tsml_eval/_wip/shapelets/classification/__init__.py
  tsml_eval/_wip/shapelets/classification/shapelet_based/__init__.py
  tsml_eval/_wip/shapelets/classification/shapelet_based/_stc.py
  tsml_eval/_wip/shapelets/shapelet_debug.py
  tsml_eval/_wip/shapelets/transformations/__init__.py
  tsml_eval/_wip/shapelets/transformations/collection/__init__.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/__init__.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/_quality_measures.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/_shapelet_transform.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/tests/__init__.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/tests/test_quality_measures.py
  tsml_eval/_wip/transformations/collection/shapelet_based/__init__.py
  tsml_eval/experiments/set_classifier.py
Labels: enhancement
