Repository time-series-machine-learning/tsml-eval, pull requests merged in 2024-10, with the labels that each got.

#291 [ENH] Base forecaster simplest version
  tsml_eval/_wip/forecasting/base.py
  tsml_eval/_wip/forecasting/ets.py
  tsml_eval/_wip/forecasting/example_uses.py
  tsml_eval/_wip/forecasting/exponential_smoothing.py
  tsml_eval/_wip/forecasting/window_base.py
Labels: enhancement

#294 [MNT] Workflow refactor and maintenance
  .codecov.yml
  .github/utilities/issue_assign.py
  .github/utilities/pr_labeler.py
  .github/utilities/pr_open_commenter.py
  .github/utilities/pr_welcome_edited.py
  .github/utilities/run_examples.sh
  .github/workflows/issue_comment_edited.yml
  .github/workflows/issue_comment_posted.yml
  .github/workflows/periodic_tests.yml
  .github/workflows/pr_examples.yml
  .github/workflows/pr_opened.yml
  .github/workflows/pr_typecheck.yml
  .pre-commit-config.yaml
  MANIFEST.in
  _tsml_research_resources/soton/iridis/iridis_python.md
  _tsml_research_resources/uea/ada/ada_python.md
  pyproject.toml
Labels: maintenance, tsml research resources

#295 [MNT] `mypy` fixes
  .github/workflows/periodic_tests.yml
  .github/workflows/pr_typecheck.yml
  pyproject.toml
  tsml_eval/publications/y2023/distance_based_clustering/_plot_path.py
Labels: maintenance

#268 [ENH] Shapelet quality measures
  .github/workflows/pr_precommit.yml
  .pre-commit-config.yaml
  tsml_eval/_wip/shapelets/classification/shapelet_based/_stc.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/_quality_measures.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/_shapelet_transform.py
  tsml_eval/_wip/shapelets/transformations/collection/shapelet_based/tests/test_quality_measures.py
  tsml_eval/experiments/classification_experiments.py
Labels: enhancement

#296 Ajb/base forecaster
  tsml_eval/_wip/forecasting/base.py
  tsml_eval/_wip/forecasting/es_comparison2.py
  tsml_eval/_wip/forecasting/ets.py
  tsml_eval/_wip/forecasting/exponential_smoothing.py
  tsml_eval/_wip/forecasting/exponential_smoothing_comparison.py
  tsml_eval/_wip/forecasting/nixtla.py
  tsml_eval/_wip/forecasting/tests/__init__.py
  tsml_eval/_wip/forecasting/tests/test_ets.py
  tsml_eval/_wip/forecasting/tests/test_window_based.py
  tsml_eval/_wip/forecasting/window_base.py
Labels: forecasting
